
services:
  # 1. 데이터베이스 (PostgreSQL)
  db:
    image: pgvector/pgvector:pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=korea_travel_db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"

  # 2. 메인 백엔드 (Django)
  django:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app:/app  # 코드 수정하면 바로 반영되게 연결 (Hot Reload)
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=korea_travel_db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    env_file:
        - ./django_app/.env

  # 3. AI 서버 (FastAPI)
  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./fastapi_app:/app # 코드 수정하면 바로 반영
    ports:
      - "8001:8000"

  # 4. 프론트엔드 (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # 브라우저에서 localhost로 접속
    depends_on:
      - django
      - fastapi

  # 5. 장소 검색 서버 (FastAPI Places)
  fastapi_places:
    build:
      context: ./fastapi_places
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./fastapi_places:/app # 코드 수정하면 바로 반영
    ports:
      - "8002:8002"
    depends_on:
      - db
      - django  # Django가 users_user 테이블을 먼저 생성
    environment:
      - DB_HOST=db
      - DB_NAME=korea_travel_db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_PORT=5432
    env_file:
      - ./fastapi_places/.env

  # [1] 프로메테우스 (데이터 수집가)
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # 설정 파일 연결
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # [2] 그라파나 (데이터 시각화)
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data: