global:
  scrape_interval: 5s # 5초마다 긁어옴

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['django:8000'] # 장고 컨테이너 이름:포트
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000'] # FastAPI 컨테이너 이름:포트 (포트 확인 필요!)